id: P009596
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:54.993258
source_metadata:
  id: bdr:W29484
  title: བུ་དོན་མ
  author: ''
  volumes:
    0ce0578fb8124ce78130b77fb27d9910:
      image_group_id: I1PD399
      title: ''
      volume_number: 1
      total_pages: 332
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
