id: P009596
initial_creation_type: ocr
source_metadata:
  id: bdr:W29484
  title: བུ་དོན་མ
  author: ''
  volumes:
    0ce0578fb8124ce78130b77fb27d9910:
      image_group_id: I1PD399
      title: ''
      volume_number: 1
      total_pages: 332
